import { promises as fs } from "node:fs";
import { join, parse } from "node:path";
import { compileFromFile } from "json-schema-to-typescript";
import pc from "picocolors";

async function findJsonFiles(dir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files: string[] = [];
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...(await findJsonFiles(fullPath)));
      } else if (entry.isFile() && entry.name.endsWith(".json")) {
        files.push(fullPath);
      }
    }
    return files;
  } catch (err: any) {
    if (err.code === "ENOENT") {
      console.error(pc.red(`Error: Schema directory '${dir}' does not exist.`));
      process.exit(1);
    }
    throw err;
  }
}

export async function generateCommand(options: {
  schemas?: string;
  out?: string;
}) {
  console.log(pc.cyan(`\n⚡ ocpp-ws-io: Generating from JSON Schemas\n`));

  if (!options.schemas || !options.out) {
    console.error(pc.red("Error: --schemas and --out arguments are required."));
    console.log(
      pc.gray(
        "Example: ocpp generate --schemas ./schemas --out ./src/generated",
      ),
    );
    process.exit(1);
  }

  const { schemas, out } = options;

  console.log(pc.gray(`Reading validation schemas from: ${schemas}`));
  console.log(pc.gray(`Outputting TypeScript typings to: ${out}\n`));

  try {
    // Ensure output directory exists
    await fs.mkdir(out, { recursive: true });

    // Recursively find all JSON schemas
    const schemaFiles = await findJsonFiles(schemas);

    if (schemaFiles.length === 0) {
      console.warn(pc.yellow(`No .json files found in ${schemas}`));
      return;
    }

    let successCount = 0;

    for (const file of schemaFiles) {
      const { name } = parse(file);
      console.log(pc.blue(`Compiling ${name}.json...`));

      try {
        const tsCode = await compileFromFile(file, {
          bannerComment:
            "/* eslint-disable */\n/**\n * This file was automatically generated by ocpp-ws-io CLI.\n * DO NOT MODIFY IT BY HAND.\n */",
          style: {
            singleQuote: false,
          },
        });

        const outFile = join(out, `${name}.ts`);
        await fs.writeFile(outFile, tsCode, "utf-8");

        console.log(pc.green(`  ✔ Generated ${outFile}`));
        successCount++;
      } catch (compileError: any) {
        console.error(
          pc.red(`  ✖ Failed to compile ${name}.json: ${compileError.message}`),
        );
      }
    }

    console.log(
      pc.cyan(
        `\n✨ Successfully generated ${successCount} TypeScript declaration files!`,
      ),
    );
  } catch (error: any) {
    console.error(pc.red(`\nGeneration failed: ${error.message}`));
    process.exit(1);
  }
}
