import { promises as fs } from "node:fs";
import { join, parse } from "node:path";
import pc from "picocolors";

export async function sdkCommand(options: { schemas?: string; out?: string }) {
  console.log(pc.cyan(`\n⚡ ocpp-ws-cli: TypeScript SDK Generator`));

  const schemaDir = join(process.cwd(), options.schemas || "./schemas");
  const outFile = join(process.cwd(), options.out || "./src/generated/sdk.ts");

  console.log(pc.gray(`Scanning schemas: ${schemaDir}`));
  console.log(pc.gray(`Output file:      ${outFile}\n`));

  try {
    const files = await fs.readdir(schemaDir, { withFileTypes: true });

    // We only care about Request payloads to generate the outbound Client SDK methods
    const requestSchemas = files
      .filter((file) => file.isFile() && file.name.endsWith("Request.json"))
      .map((file) => parse(file.name).name.replace("Request", ""));

    if (requestSchemas.length === 0) {
      console.log(
        pc.yellow(`No *Request.json schemas found in the target directory.`),
      );
      process.exit(1);
      return;
    }

    console.log(pc.blue(`Found ${requestSchemas.length} API Definitions.`));
    console.log(pc.gray(`Generating SDK wrappers...`));

    // We assume `ocpp generate` was already run and output the raw Types in `types.ts`
    let sdkCode = `/**\n * Auto-generated OCPP Client SDK \n * Generated by ocpp-ws-cli\n */\n\n`;

    sdkCode += `import { OCPPClient } from "ocpp-ws-io";\n`;
    sdkCode += `import type {\n`;
    for (const method of requestSchemas) {
      sdkCode += `  ${method}Request,\n`;
      sdkCode += `  ${method}Response,\n`;
    }
    sdkCode += `} from "./types.js";\n\n`; // Assumes generated types are in the same output folder

    sdkCode += `export class OCPPApiClient {\n`;
    sdkCode += `  constructor(public client: OCPPClient) {}\n\n`;

    for (const method of requestSchemas) {
      // e.g. lowerCamelCase "bootNotification"
      const methodName = method.charAt(0).toLowerCase() + method.slice(1);

      sdkCode += `  /** Execute a ${method} request (OCPP 1.6) */\n`;
      sdkCode += `  public async ${methodName}(payload: ${method}Request): Promise<${method}Response> {\n`;
      sdkCode += `     return await this.client.call("ocpp1.6", "${method}", payload) as ${method}Response;\n`;
      sdkCode += `  }\n\n`;
    }

    sdkCode += `}\n`;

    // Write file
    const outDir = parse(outFile).dir;
    await fs.mkdir(outDir, { recursive: true });
    await fs.writeFile(outFile, sdkCode, "utf-8");

    console.log(pc.green(`\n✔ Success! SDK generated at ${outFile}`));
    console.log(pc.yellow(`Usage in your frontend:`));
    console.log(pc.gray(`  const api = new OCPPApiClient(client);`));
    console.log(pc.gray(`  const res = await api.bootNotification({...});`));
  } catch (error: any) {
    if (error.code === "ENOENT") {
      console.error(
        pc.red(`\nError: Schema directory '${schemaDir}' does not exist.`),
      );
      console.log(
        pc.yellow(
          `Run 'ocpp init' to scaffold a project, or point to your JSON schemas.`,
        ),
      );
    } else {
      console.error(pc.red(`\nGeneration failed: ${error.message}`));
    }
    process.exit(1);
  }
}
