import {
  extractMethods,
  extractSendMethods,
  generateVersionFile,
  type MethodSchemas,
  type SchemaEntry,
  type VersionConfig,
} from "../../codegen/generator.js";

/** What `ocpp generate` writes for one protocol. */
export interface ProtocolFiles {
  /** The protocol's names: types file, CALL and SEND maps. */
  version: VersionConfig;
  /** The validator's export name, such as `vendorProtoValidator`. */
  validatorName: string;
  methods: Map<string, MethodSchemas>;
  sendMethods: Map<string, SchemaEntry>;
  /** File contents by file name. */
  files: Map<string, string>;
}

/**
 * The types of one protocol, the augmentation that declares them to
 * ocpp-ws-io, and its validator, all from the same schemas, so the types and
 * what strict mode validates cannot drift apart.
 *
 * @param schema The schema entries, each with an `$id`.
 * @param protocol The subprotocol, such as "vendor-proto".
 * @param source The schema file or URL, named in the files' headers.
 */
export function generateProtocolFiles(
  schema: SchemaEntry[],
  protocol: string,
  source: string,
): ProtocolFiles {
  const safeName = protocol
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
  const typeName = safeName.charAt(0).toUpperCase() + safeName.slice(1);
  const valueName = safeName.charAt(0).toLowerCase() + safeName.slice(1);

  const version: VersionConfig = {
    key: safeName.toLowerCase(),
    file: source,
    mapName: `${typeName}Methods`,
    sendMapName: `${typeName}SendMethods`,
    protocol,
  };
  const validatorName = `${valueName}Validator`;
  const methods = extractMethods(schema);
  const sendMethods = extractSendMethods(schema);
  const protocolLiteral = JSON.stringify(protocol);

  const files = new Map<string, string>();
  files.set(
    `${version.key}.ts`,
    generateVersionFile(version, methods, sendMethods, {
      typesModule: "ocpp-ws-io",
    }),
  );

  // A protocol without SEND messages needs no OCPPSendMethodMap entry.
  const hasSend = sendMethods.size > 0;
  const imported = hasSend
    ? `${version.mapName}, ${version.sendMapName}`
    : version.mapName;
  files.set(
    "augment.d.ts",
    [
      "// Auto-generated by ocpp-ws-cli — DO NOT EDIT",
      "/* eslint-disable */",
      "",
      `import type { ${imported} } from "./${version.key}.js";`,
      "",
      `declare module "ocpp-ws-io" {`,
      "  interface OCPPMethodMap {",
      `    ${protocolLiteral}: ${version.mapName};`,
      "  }",
      ...(hasSend
        ? [
            "  interface OCPPSendMethodMap {",
            `    ${protocolLiteral}: ${version.sendMapName};`,
            "  }",
          ]
        : []),
      "}",
      "",
    ].join("\n"),
  );

  files.set(
    `${version.key}.validator.ts`,
    [
      `// Auto-generated by ocpp-ws-cli from ${source} — DO NOT EDIT`,
      "/* eslint-disable */",
      "",
      'import { createValidator } from "ocpp-ws-io";',
      "",
      `/** The JSON schemas of ${protocolLiteral}. */`,
      `const schemas: Parameters<typeof createValidator>[1] = ${JSON.stringify(schema, null, 2)};`,
      "",
      "/**",
      ` * Validates ${protocolLiteral} messages in strict mode:`,
      ` * \`strictModeValidators: [${validatorName}]\`. The types, from the same`,
      ` * schemas, are in ./${version.key}.ts.`,
      " */",
      `export const ${validatorName} = createValidator(${protocolLiteral}, schemas);`,
      "",
    ].join("\n"),
  );

  return { version, validatorName, methods, sendMethods, files };
}
