name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Even better if you can include a code snippet!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. create a client with...
        2. send a call...
        3. see error...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node.js version, OS, browser (if applicable)
      placeholder: Node v18.17.0, Windows 11
    validations:
      required: true
  - type: dropdown
    id: ocpp-version
    attributes:
      label: OCPP Version
      options:
        - OCPP 1.6
        - OCPP 2.0.1
        - OCPP 2.1
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched for existing issues that match this bug
          required: true
